version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm run build  
  post_build:
    commands:
      - aws s3 sync build s3://ilu-onboarding --delete
      - aws cloudfront create-invalidation --distribution-id E2DJX2U2HHE5YM --paths "/*"